name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: find . -maxdepth 1 -type d \( ! -name . \) -exec bash -c 'cd "$0" && npm install' {} \; 
      - name: Build
        run: find . -maxdepth 1 -type d \( ! -name . \) -exec bash -c 'cd "$0" && npm run build' {} \; 
      - name: Move
        run:
          mkdir dist
          find . -mindepth 1 -maxdepth 2 -type d -name TP* -exec bash -c 'mv "$0" dist/' {} \;
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}