name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          pushd TP1; npm install; popd
          pushd TP2; npm install; popd
          pushd TP3; npm install; popd
          pushd TP4; npm install; popd
          pushd TP5; npm install; popd
          pushd Project; npm install; popd
          pushd Prod; npm install; popd
      - name: Set Base URL
        run: |
          sed -i 's/parcel build .\/src\/index\.html/parcel build .\/src\/index\.html --no-minify --public-url \/TP1\//g' TP1/package.json
          sed -i 's/parcel build .\/src\/index\.html/parcel build .\/src\/index\.html --no-minify --public-url \/TP2\//g' TP2/package.json
          sed -i 's/parcel build .\/src\/index\.html/parcel build .\/src\/index\.html --no-minify --public-url \/TP3\//g' TP3/package.json
          sed -i 's/parcel build .\/src\/index\.html/parcel build .\/src\/index\.html --no-minify --public-url \/TP4\//g' TP4/package.json
          sed -i 's/parcel build .\/src\/index\.html/parcel build .\/src\/index\.html --no-minify --public-url \/TP5\//g' TP5/package.json
          sed -i 's/parcel build .\/src\/index\.html/parcel build .\/src\/index\.html --no-minify --public-url \/Project\//g' Project/package.json
          sed -i 's/parcel build .\/src\/index\.html/parcel build .\/src\/index\.html --no-minify --public-url \/Prod\//g' Prod/package.json
      - name: Build
        run: |
          pushd TP1; npm run build; popd
          pushd TP2; npm run build; popd
          pushd TP3; npm run build; popd
          pushd TP4; npm run build; popd
          pushd TP5; npm run build; popd
          pushd Project; npm run build; popd
          pushd Prod; npm run build; popd
      - name: Copy
        run: |
          mkdir -p public/TP1
          cp TP1/dist/* public/TP1/
          mkdir -p public/TP2
          cp TP2/dist/* public/TP2/
          mkdir -p public/TP3
          cp TP3/dist/* public/TP3/
          mkdir -p public/TP4
          cp TP4/dist/* public/TP4/
          mkdir -p public/TP5
          cp TP5/dist/* public/TP5/
          mkdir -p public/Project
          cp Project/dist/* public/Project/
          mkdir -p public/Prod
          cp Prod/dist/* public/Prod/
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}