name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: 
          pushd TP1; npm install; popd
          pushd TP2; npm install; popd
      - name: Build
        run:
          pushd TP1; npm run build; popd
          pushd TP2; npm run build; popd
      - name: Copy
        run:
          mkdir -p dist/TP1
          cp TP1/dist/* public/TP1/
          mkdir -p dist/TP2
          cp TP2/dist/* public/TP2/
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}